language: php

os:
  - linux

env:
  global:
    # fix "Xdebug 3 is installed by default, breaking builds"
    # see https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748
    - XDEBUG_MODE=coverage

services:
  - mysql
  - postgresql

jobs:
  fast_finish: true
  include:
    # 1) sqlite, previous MW LTS stable
    - env: DB=sqlite; MW=REL1_31; PHPUNIT=6.5.*
      php: 7.1
    # 2) postgres, current MW non-LTS stable
    - env: DB=postgres; MW=REL1_34; PHPUNIT=6.5.*
      php: 7.2
    # 3) mysql, current MW LTS stable, COVERAGE
    - env: DB=mysql; MW=REL1_35; PHPUNIT=8.5.*; TYPE=coverage
      php: 7.3

before_install:
  # MW is not yet compatible with Composer 2.x, see https://phabricator.wikimedia.org/T266417
  - composer self-update --1
  - wget https://raw.githubusercontent.com/SemanticMediaWiki/CIScripts/main/travis/install-mediawiki.sh

install:
  - bash ./install-mediawiki.sh
  - bash ./build/travis/install-semantic-drilldown.sh

script:
  - bash ./build/travis/run-tests.sh

cache:
  directories:
    - $HOME/.composer/cache
